"""empty message

Revision ID: 372b4110b4f7
Revises: 1db9a4bf6bed
Create Date: 2024-12-21 01:45:09.980617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372b4110b4f7'
down_revision: Union[str, None] = '1db9a4bf6bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
