"""empty message

Revision ID: 92bb825d2b52
Revises: 9bddb9205c9b
Create Date: 2024-12-18 16:59:04.296147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bb825d2b52'
down_revision: Union[str, None] = '9bddb9205c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logo', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('banner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'banner')
    op.drop_column('businesses', 'logo')
    # ### end Alembic commands ###
