"""empty message

Revision ID: 0b70dfc6ebec
Revises: 372b4110b4f7
Create Date: 2024-12-21 02:10:10.697452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b70dfc6ebec'
down_revision: Union[str, None] = '372b4110b4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['profile_picture'])
    op.add_column('posts', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['avatar'], ['profile_picture'], ondelete='CASCADE')

    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('posts', 'avatar')
    # ### end Alembic commands ###
