"""Add ondelete cascade to foreign keys

Revision ID: 9b69665eb060
Revises: ce3af1327132
Create Date: 2024-12-07 17:19:42.034154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b69665eb060'
down_revision: Union[str, None] = 'ce3af1327132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('businesses_seller_id_fkey', 'businesses', type_='foreignkey')
    op.create_foreign_key(None, 'businesses', 'users', ['seller_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.drop_constraint('favorites_post_id_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('follows_follower_id_fkey', 'follows', type_='foreignkey')
    op.drop_constraint('follows_followed_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['post_id'])
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_followed_id_fkey', 'follows', 'users', ['followed_id'], ['user_id'])
    op.create_foreign_key('follows_follower_id_fkey', 'follows', 'users', ['follower_id'], ['user_id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('favorites_post_id_fkey', 'favorites', 'posts', ['post_id'], ['post_id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['post_id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.create_foreign_key('businesses_seller_id_fkey', 'businesses', 'users', ['seller_id'], ['user_id'])
    # ### end Alembic commands ###
