"""Initial migration

Revision ID: d213d43e38da
Revises: c14731a71484
Create Date: 2024-11-29 19:42:19.929394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd213d43e38da'
down_revision: Union[str, None] = 'c14731a71484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_businesses_id', table_name='businesses')
    op.drop_constraint('businesses_owner_id_fkey', 'businesses', type_='foreignkey')
    op.create_foreign_key(None, 'businesses', 'users', ['owner_id'], ['owner_id'])
    op.add_column('users', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'owner_id')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.create_foreign_key('businesses_owner_id_fkey', 'businesses', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_businesses_id', 'businesses', ['id'], unique=False)
    op.alter_column('businesses', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
